import { StyleSheet } from 'react-native';

// Shared styles for the find detail modal and its subcomponents.
export const findDetailStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
  },
  posterSafeArea: {
    flex: 1,
    backgroundColor: '#fafaf9',
  },
  posterModalContent: {
    padding: 20,
  },
  sheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '90%',
    overflow: 'hidden',
  },
  content: {
    padding: 20,
    gap: 18,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  posterButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#fff',
    minHeight: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  posterText: {
    fontWeight: '800',
    color: '#0f172a',
    fontSize: 15,
  },
  hero: {
    width: '100%',
    height: 280,
    borderRadius: 14,
    backgroundColor: '#f3f4f6',
  },
  metaRow: {
    gap: 8,
  },
  metaText: {
    color: '#0f172a',
    fontSize: 18,
    fontWeight: '800',
  },
  metaSubtle: {
    color: '#6b7280',
    fontSize: 14,
    fontWeight: '700',
  },
  presetRow: {
    gap: 10,
  },
  presetButton: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  presetPrimary: {
    backgroundColor: '#0f172a',
    borderColor: '#0f172a',
  },
  presetText: {
    color: '#0f172a',
    fontWeight: '800',
    fontSize: 15,
  },
  presetTextPrimary: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 15,
  },
  identifyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  aiCard: {
    marginTop: 10,
    padding: 14,
    borderRadius: 12,
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    gap: 8,
  },
  aiTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0f172a',
  },
  aiSection: {
    gap: 4,
    marginTop: 4,
  },
  applyButton: {
    marginTop: 6,
    backgroundColor: '#111',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  applyText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 15,
  },
  identifyButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#0f172a',
    backgroundColor: '#fff',
    alignItems: 'center',
    minWidth: 120,
  },
  identifyText: {
    color: '#0f172a',
    fontWeight: '800',
    fontSize: 14,
  },
  errorText: {
    color: '#b91c1c',
    fontWeight: '800',
    marginTop: 6,
  },
  section: {
    gap: 8,
  },
  label: {
    fontSize: 17,
    fontWeight: '800',
    color: '#111',
  },
  labelInput: {
    borderWidth: 2,
    borderColor: '#cbd5e1',
    borderRadius: 14,
    padding: 14,
    fontSize: 18,
    color: '#0f172a',
    backgroundColor: '#f8fafc',
  },
  input: {
    minHeight: 120,
    borderWidth: 2,
    borderColor: '#cbd5e1',
    borderRadius: 14,
    padding: 14,
    textAlignVertical: 'top',
    fontSize: 16,
    color: '#0f172a',
    backgroundColor: '#f8fafc',
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    minWidth: 112,
    alignItems: 'center',
  },
  chipSelected: {
    backgroundColor: '#111',
    borderColor: '#111',
  },
  chipText: {
    color: '#111',
    fontWeight: '800',
    fontSize: 15,
  },
  chipTextSelected: {
    color: '#fff',
  },
  favoriteChip: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f8fafc',
    alignItems: 'center',
  },
  favoriteChipActive: {
    backgroundColor: '#111',
    borderColor: '#111',
  },
  favoriteText: {
    color: '#111',
    fontWeight: '800',
    fontSize: 15,
  },
  favoriteTextActive: {
    color: '#fff',
  },
  actions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 14,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: '#111',
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
  },
  primaryText: {
    color: '#fff',
    fontSize: 19,
    fontWeight: '800',
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: '#fff',
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  secondaryText: {
    color: '#111',
    fontSize: 19,
    fontWeight: '800',
  },
  backButton: {
    marginTop: 4,
    backgroundColor: '#f8fafc',
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  backButtonText: {
    color: '#0f172a',
    fontSize: 16,
    fontWeight: '800',
  },
  hint: {
    color: '#6b7280',
    fontSize: 12,
    textAlign: 'center',
  },
});
